[Library]
others = /opt/intelFPGA_lite/17.0/modelsim_ase/std
std = /opt/intelFPGA_lite/17.0/modelsim_ase/std
ieee = /opt/intelFPGA_lite/17.0/modelsim_ase/ieee
vl = /opt/intelFPGA_lite/17.0/modelsim_ase/verilog
vital2000 = /opt/intelFPGA_lite/17.0/modelsim_ase/vital2000
vital1995 = /opt/intelFPGA_lite/17.0/modelsim_ase/vital1995
synopsys = /opt/intelFPGA_lite/17.0/modelsim_ase/synopsys
modelsim_lib = /opt/intelFPGA_lite/17.0/modelsim_ase/modelsim_lib
altera_mf = /opt/intelFPGA_lite/17.0/modelsim_ase/altera/vhdl/altera_mf
altera = /opt/intelFPGA_lite/17.0/modelsim_ase/altera/vhdl/altera
altera_lnsim = /opt/intelFPGA_lite/17.0/modelsim_ase/altera/vhdl/altera_lnsim
work = work
[vcom]
; VHDL93 variable selects language version as the default. 
; Default is VHDL-2002.
; Value of 0 or 1987 for VHDL-1987.
; Value of 1 or 1993 for VHDL-1993.
; Default or value of 2 or 2002 for VHDL-2002.
; Value of 3 or 2008 for VHDL-2008.
VHDL93 = 1993

[vsim]
; Simulator resolution
; Set to fs, ps, ns, us, ms, or sec with optional prefix of 1, 10, or 100.
Resolution = ps