#ifndef MINIMIG_ETH_ABI_H
#define MINIMIG_ETH_ABI_H

// Generated by extra/gen_eth_abi.py. Do not edit by hand.
// Shared-memory ABI constants consumed by the HPS bridge.

// Shared-memory offsets and queue layout.
#define ETH_CTRL_FLAGS         0x1000       // 4 bytes - control flags
#define ETH_CTRL_REGS          0x1004       // legacy/debug register mirror block
#define ETH_CTRL_MAC           0x104C       // 6 bytes - MAC address
#define ETH_CTRL_STATUS        0x1052       // 2 bytes - transport status
#define ETH_CTRL_STATS         0x1054       // 52 bytes - HPS statistics
#define ETH_HPS_HEARTBEAT      0x1088       // 4 bytes - HPS heartbeat counter
#define ETH_HPS_SIGNATURE      0x108C       // 4 bytes - HPS signature word
#define ETH_HPS_SIGNATURE_MAGIC 0xCAFEBABE   // magic value written by the HPS bridge
#define ETH_RTL8019_STATE      0x1100       // FPGA-owned RTL8019 state/debug mirror
// Integrity probe (sync slots 40/41): the bg publishes a running byte-sum of the
// payload it writes into the RX ring (RX_CSUM) and a count of frames delivered
// (RX_FRAMES). The daemon keeps the same running sum + count for the frames it
// enqueues and compares them ONLY when the counts match (bg caught up) so a
// "sums equal" verdict is trustworthy. Both are byte-swapped by the mailbox.
#define ETH_RTL8019_RX_CSUM    (ETH_RTL8019_STATE + 0x0A)  // 0x110A
#define ETH_RTL8019_RX_FRAMES  (ETH_RTL8019_STATE + 0x0C)  // 0x110C
// Read-side integrity probe (sync slots 42/43): ring_wr_csum = bytes the bg WROTE
// into the NE2000 ring; dp_rd_csum = bytes the 68k READ back via the data port. At
// a ring drain they match iff the 68k reads the ring intact -- splits a data-port
// read corruption (RTL-fixable) from an Amiga-side drop. Both byte-swapped.
#define ETH_RTL8019_RING_WR    (ETH_RTL8019_STATE + 0x0E)  // 0x110E
#define ETH_RTL8019_DP_RD      (ETH_RTL8019_STATE + 0x10)  // 0x1110
// Per-frame read-corruption probe (slot 44): count of even-length payload reads
// where the 68k pulled different bytes than the bg wrote (keyed by ring page, no
// peek confound). >0 = data-port READ corruption proven; ==0 = read is clean.
#define ETH_RTL8019_RD_CORRUPT (ETH_RTL8019_STATE + 0x12)  // 0x1112
// Count of payload reads actually compared (slot 45). 0 => the probe never armed
// (the driver reads the ring differently than assumed) -> a rdCorrupt=0 is then
// inconclusive, not "clean". >0 with rdCorrupt=0 = reads PROVEN clean.
#define ETH_RTL8019_RD_CHECKED (ETH_RTL8019_STATE + 0x14)  // 0x1114
// Write/storage read-back probe (slots 46/47): the bg re-reads one-page RX
// payloads through packet-RAM port A and compares them against frame_wr_csum.
#define ETH_RTL8019_RB_BAD       (ETH_RTL8019_STATE + 0x16)  // 0x1116
#define ETH_RTL8019_RB_CSUM_RUN  (ETH_RTL8019_STATE + 0x18)  // 0x1118
// Last per-frame read-probe mismatch checksum details (slots 48/49).
#define ETH_RTL8019_RD_BAD_EXP   (ETH_RTL8019_STATE + 0x1A)  // 0x111A
#define ETH_RTL8019_RD_BAD_ACT   (ETH_RTL8019_STATE + 0x1C)  // 0x111C
// TX-path probes. TX_MIRROR_* is the running byte-sum/count of frames captured
// from Amiga data-port writes into the FPGA ping-pong TX mirror. TX_DRAIN_* is
// the running byte-sum/count of bytes drained from that mirror into ETH_TX_BUFFER.
// The HPS reports TXH for the bytes it reads/sends from ETH_TX_BUFFER.
#define ETH_RTL8019_TX_MIRROR_CSUM   (ETH_RTL8019_STATE + 0x1E)  // 0x111E
#define ETH_RTL8019_TX_MIRROR_FRAMES (ETH_RTL8019_STATE + 0x20)  // 0x1120
#define ETH_RTL8019_TX_DRAIN_CSUM    (ETH_RTL8019_STATE + 0x22)  // 0x1122
#define ETH_RTL8019_TX_DRAIN_FRAMES  (ETH_RTL8019_STATE + 0x24)  // 0x1124
#define ETH_RTL8019_TX_MIRROR_BYTES  (ETH_RTL8019_STATE + 0x26)  // 0x1126
#define ETH_RTL8019_TX_DRAIN_BYTES   (ETH_RTL8019_STATE + 0x28)  // 0x1128
#define ETH_PACKET_BUFFER_SIZE 0x0600       // 1536-byte staged frame capacity
#define ETH_TX_BUFFER          0x2000       // staged TX buffer
#define ETH_RX_BUFFER          0x2600       // legacy staged RX buffer
#define ETH_PACKET_INFO        0x2C00       // packet metadata area
#define ETH_TX_REQUEST_ADDR    0x2C00       // single-slot TX request start address in NE space
#define ETH_TX_REQUEST_LEN     0x2C02       // single-slot TX request length in bytes
#define ETH_RX_QUEUE_HEAD      0x2C04       // low byte: FPGA-consumed shared RX queue head
#define ETH_RX_QUEUE_TAIL      0x2C06       // low byte: HPS-produced shared RX queue tail
#define ETH_TX_REQUEST_SEQ     0x2C08       // single-slot TX request sequence number
#define ETH_TX_COMPLETE_SEQ    0x2C0A       // HPS completion sequence for the last TX request
#define ETH_RX_QUEUE_LEN       0x2C20       // uint16_t lengths for shared RX slots
#define ETH_NE_MEMORY          0x3000       // compact 16KB NE packet RAM backing store
#define ETH_DEBUG_INFO         0x7000       // debug/status region
#define ETH_FUTURE_USE         0x9000       // reserved/shared queue backing
#define ETH_RX_QUEUE_SLOTS     0x10         // shared RX queue slot count
#define ETH_RX_QUEUE_DATA      ETH_FUTURE_USE // payload base for shared RX queue slots

// Shared control flags.
#define ETH_FLAG_RESET         0x0001       // legacy HPS-side reset request
#define ETH_FLAG_TX_REQ        0x0002       // FPGA requests HPS transmit service
#define ETH_FLAG_RX_AVAIL      0x0004       // shared RX queue is non-empty
#define ETH_FLAG_IRQ           0x0008       // FPGA interrupt state mirror
#define ETH_FLAG_ENABLED       0x0020       // FPGA reports NIC enabled state
#define ETH_FLAG_HPS_OWNED_MASK (ETH_FLAG_RESET) // bits written by the HPS bridge
#define ETH_FLAG_HPS_ACK_MASK  (ETH_FLAG_TX_REQ) // bits HPS clears to acknowledge FPGA work
#define ETH_FLAG_FPGA_MIRROR_MASK (ETH_FLAG_TX_REQ | ETH_FLAG_IRQ | ETH_FLAG_ENABLED) // FPGA-owned flag mirror bits

// Shared transport status bits.
#define ETH_STATUS_TX_OK       0x0001       // last transmit completed successfully
#define ETH_STATUS_TX_ERR      0x0002       // last transmit failed
#define ETH_STATUS_LINK_UP     0x0004       // bridge reports link present
#define ETH_STATUS_FULL_DUPLEX 0x0008       // bridge reports full-duplex link
#define ETH_STATUS_FPGA_SAMPLED    0x0100  // FPGA sampled the HPS heartbeat/signature area
#define ETH_STATUS_FPGA_SIGNATURE  0x0200  // FPGA saw the HPS signature magic
#define ETH_STATUS_FPGA_HEARTBEAT  0x0400  // FPGA saw a non-zero HPS heartbeat
#define ETH_STATUS_FPGA_HB_CHANGED 0x0800  // FPGA saw the HPS heartbeat advance
#define ETH_STATUS_FPGA_COMM_OK    0x1000  // FPGA sees a valid, advancing HPS endpoint
#define ETH_STATUS_FPGA_RX_ACTIVE  0x2000  // FPGA RX polling is active
#define ETH_STATUS_FPGA_TX_PENDING 0x4000  // FPGA has a pending TX request

#endif  // MINIMIG_ETH_ABI_H
